schema_version: 1

context:
  name: django-etc
  version: 1.4.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django-etc-${{ version }}.tar.gz
  sha256: fa7dbcdba5d0dd3b42eac54463fe24a9e1202a1492ecbf50ed0bc1555074af8f

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - etc
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Tiny stuff for Django that won't fit into separate apps.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/idlesign/django-etc

extra:
  recipe-maintainers:
    - rxm7706
